### ISSUE TITLE
Broken Murloc Textures in Black Phantom Deeps

### ISSUE THREAD

**Issue by MasterBruin** [redmagejoe/TurtleHD#11]
Hello,
I recently found out, that all Murlocs inside the dungeon Black Phantom Deeps, have broken textures. Also the Murloc boss "Gelihast".

**Comment by redmagejoe** [comment]
This is known and is being looked at.

**Comment by redmagejoe** [comment]
Attempting fix in https://github.com/redmagejoe/TurtleHD/commit/253fd8a2fad60e801d65b88b9584b71e67db919a

**Comment by redmagejoe** [comment]
Fixed on test branch, will be pushed to main branch in v1.17.1-1.0c
