### ISSUE TITLE
The spell introduction in Simplified Chinese is missing

### ISSUE THREAD

**Issue by luomoxu** [redmagejoe/TurtleHD#15]
add patch
![Snipaste_2023-12-02_10-10-15](https://github.com/redmagejoe/TurtleHD/assets/1317574/5a6c9a36-3c4a-45c3-acef-673ff012a999)
without patch
![Snipaste_2023-12-02_10-11-13](https://github.com/redmagejoe/TurtleHD/assets/1317574/a94489e8-de72-431f-83fe-f1443b216cd7)

**Comment by redmagejoe** [comment]
We do not support the Chinese localization with this patch.
