### ISSUE TITLE
Patch A makes camera higher while on flying mounts.

### ISSUE THREAD

**Issue by StrayDemon-13** [redmagejoe/TurtleHD#16]
Whenever I'm on a griffon(or any flying mount), the camera focal point moves very high up and my character goes to the bottom of the screen. It goes back to normal when I dismount. Tested on the 20231128 version.

**Camera height with Patch A.**
![WoWScrnShot_120223_015118](https://github.com/redmagejoe/TurtleHD/assets/152682456/7d89f080-2037-4839-b29a-3c5836aa03b4)

**Camera height without Patch A.**
![WoWScrnShot_120223_150529](https://github.com/redmagejoe/TurtleHD/assets/152682456/9e832184-d0a7-4744-999a-58b8d7fc229b)

**Comment by redmagejoe** [comment]
Known, but no current way to fix this.  Would require input from someone familiar with camera points attached to the models for flying mounts.

**Comment by redmagejoe** [comment]
Fixed in latest release.
