### ISSUE TITLE
Client crashed because of hunter's pet

### ISSUE THREAD

**Issue by hbltth** [redmagejoe/TurtleHD#17]
Hi sometimes my client crashed on the character selection page when I tried to choose my Tauren Hunter and the pet wasn't dismissed, a error frame was popped up. If pet was dismissed the crash would not occur.

**Comment by hbltth** [comment]
I found it happens when I switch between my Warlock and Hunter.

**Comment by hbltth** [comment]
Hunter's pet conflict with Warlock's pet I think.

**Comment by redmagejoe** [comment]
Need to look into this.  Male Taurens in particular cause a number of issues on the character select screen, especially with the high-poly Scythe of Elune model.  It seems to be related to too many moving elements and a lack of sufficient memory allocated to the client.

**Comment by redmagejoe** [comment]
Duplicate of or related to #7
