### ISSUE TITLE
High Elven Npcs Broken

### ISSUE THREAD

**Issue by asdfasqw** [redmagejoe/TurtleHD#21]
Alot of the High Elven NPC's For Mobs Are Broken Including Sentinels And Mana Wyrms
![Screenshot 2024-01-18 205833](https://github.com/redmagejoe/TurtleHD/assets/132634381/a62bb66b-307f-400a-93ef-c0e4e82c8491)
![Screenshot 2024-01-18 205849](https://github.com/redmagejoe/TurtleHD/assets/132634381/46852a6e-ee36-4bf3-adf1-818de8d81e93)
![Screenshot 2024-01-18 210058](https://github.com/redmagejoe/TurtleHD/assets/132634381/766aa565-0e1d-4724-8b27-d35f0e1dae11)
![Screenshot 2024-01-18 210110](https://github.com/redmagejoe/TurtleHD/assets/132634381/0c8d204b-ee82-4aef-b083-25919577b1e8)
if you have a fix i only deleted the sound spell folder out of patch a

**Comment by asdfasqw** [comment]
small minor problem is i have screen tearing on taurren and dwarf login screen i don't know if deleting the character files will fix this or not
![Screenshot 2024-01-18 212010](https://github.com/redmagejoe/TurtleHD/assets/132634381/2a89e672-5a64-44b3-b0a3-f961f42a6e8d)
![Screenshot 2024-01-18 212044](https://github.com/redmagejoe/TurtleHD/assets/132634381/3ecdad14-0c28-4c99-a101-13eb6b238f7a)

**Comment by redmagejoe** [comment]
The latest release on the Releases page (v0.0.14-test.2) should fix this issue.  The color banding on character select is a graphics driver or WoW video settings issue, and cannot be fixed by any updates of the MPQs.
