### ISSUE TITLE
Patch-A: Bugged texture on dwarf character select screen

### ISSUE THREAD

**Issue by Tyloris** [redmagejoe/TurtleHD#22]
I've had this issue in every version of the HD Pack. In earlier releases, in the most recent release, and even in the hotfix release. I've tried a couple things: a fresh install of Turtle WoW, having only patch-A added, in both my C:/ and D:/ drives, using both the patch-A and patch-Z hotfix, replacing patch-A with a renamed patch-Z, trying both WoW.exe and WoWFoV.exe... I'm just not sure how to fix it on my end. I haven't seen any reports on the Turtle HD thread or github, so maybe this is just me?

![image](https://github.com/redmagejoe/TurtleHD/assets/66190041/39895a79-9667-4512-9af5-8b5c6abd5b7f)

**Comment by redmagejoe** [comment]
This is an issue related to WoW video settings or a graphics driver configuration.  It is not something that can be fixed through the MPQs.
