### ISSUE TITLE
Wyverns in Highperch don't have attack animations

### ISSUE THREAD

**Issue by BatuKhan** [redmagejoe/TurtleHD#23]
As the subject says, the wyverns in Highperch have no attack animation. They move around fine and run up to you when you attack, but then they just stand there. You can hear their attacks, but they are not moving. When they die, you hear their dying growl, but they remain static. The corpses are frozen in a standing position.

![image](https://github.com/redmagejoe/TurtleHD/assets/5974112/9883b72a-5487-46b8-870a-fd54a8293b5f)

**Comment by redmagejoe** [comment]
Fixed in Release 1.0b
