### ISSUE TITLE
Mounts weird texturing

### ISSUE THREAD

**Issue by torrenteeselkmanda** [redmagejoe/TurtleHD#26]
![Screenshot_2](https://github.com/redmagejoe/TurtleHD/assets/68659490/0405780c-4fdc-469f-b9a1-2daef98a1113)
Many mounts have scrambled/missing textures. Running clean version of turtle HD without any extra .MPQ

**Comment by redmagejoe** [comment]
This has been fixed. Please be sure to delete WDB and install the latest version of patch-A.
