### ISSUE TITLE
Role model error

### ISSUE THREAD

**Issue by Janbdjbd** [redmagejoe/TurtleHD#28]
If I install the patch-A.MPQ patch on the Chinese client, there will be a character model error, but if I install it on the English client, it will display normally. Can it be fixed![image](https://github.com/redmagejoe/TurtleHD/assets/148673065/cd8debc4-0517-4f9f-b243-abce047014bf)![image](https://github.com/redmagejoe/TurtleHD/assets/148673065/f4a76cac-f939-4050-92e0-c0ac7e161598)![image](https://github.com/redmagejoe/TurtleHD/assets/148673065/695b8ec3-0b12-431e-826e-d11af4a463e8)

**Comment by redmagejoe** [comment]
A separate branch for Chinese realm support will not be worked on.

Will not fix.
