### ISSUE TITLE
Image Distortion

### ISSUE THREAD

**Issue by Baudin999** [redmagejoe/TurtleHD#31]
I have freshly installed Turtle WoW and am only using vanilla tweaks. When I install patch-A.MPQ I see this:

![Screenshot 2024-07-04 215315](https://github.com/redmagejoe/TurtleHD/assets/2974147/5cd3f347-e4eb-4c24-a449-4ba71c395272)

**Comment by redmagejoe** [comment]
Make sure to delete your WDB (cache) folder before starting the game.  Make sure patch-A.MPQ is the only custom patch you have, and then try again.

Also, do you have an nVidia GPU or an AMD GPU?  AMD GPUs are known to have problems with WoW in general, which are only exacerbated by the HD patch, as the client was designed with nVidia and nVidia alone in mind back in 2004.

**Comment by Baudin999** [comment]
Hi, I am using an nVidia 4080
With your help it was solved! Thank you very much. I will close this ticket.
