### ISSUE TITLE
Can we move HD from 3.3.5a to turtle wow?

### ISSUE THREAD

**Issue by a3102397** [redmagejoe/TurtleHD#6]
There is a 3.3.5a HD project, it has many beautiful model and texture. Can we move it from 3.3.5a to turtle wow?
https://ezwow.org/topic/116445-hd-klient-obnovlyonnyj-pod-minimum-gliukov/page-1

**Comment by redmagejoe** [comment]
The way that the 3.3.5a client handles models and textures is significantly different from how the 1.12.1 client handles resources.  Entire DBCs would have to be transcribed, there would be significantly more discrepancies with base Turtle, which would make doing DIFFing much more time and labor intensive, and simply put, there are some 3.3.5a assets which simply cannot be properly downported to 1.12.1 with an automated tool, and thus would demand manual graphic tweaking.

I'm sorry, but this is not currently on our list of planned changes.  Please reserve feature requests for the forums.  This is for bugs related to the patch.
