### ISSUE TITLE
T2 priest head

### ISSUE THREAD

**Issue by shikulja** [redmagejoe/TurtleHD#9]
![image](https://github.com/redmagejoe/TurtleHD/assets/3386359/7fc17b0c-9751-4444-98f6-f232568d2a51)

**Comment by shikulja** [comment]
![image](https://github.com/redmagejoe/TurtleHD/assets/3386359/37fefd4d-b0ac-476b-9725-7dbbc87c3f2d)

https://www.wowhead.com/classic/item=22302/ironweave-cowl

**Comment by redmagejoe** [comment]
Is this still an issue on the current version?  Cannot reproduce.
